openapi: 3.0.0
tags:
  - name: Business Partners
  - name: User Preferences
  - name: Inland Provider Route Records
info:
  title: Internal API
  version: 1.0.0
paths:
  '/api/v1/organizations/{orgId}/references/{code}':
    $ref: 'paths/api@v1@organizations@{orgId}@references@{code}.yaml'
  /api/v1/user/profiles:
    $ref: paths/api@v1@user@profiles.yaml
  '/api/v1/organizations/{orgId}/references':
    $ref: 'paths/api@v1@organizations@{orgId}@references.yaml'
  /api/v1/retroPartyAdded:
    $ref: paths/api@v1@retroPartyAdded.yaml
  /api/v1/routeRecords:
    $ref: paths/api@v1@routeRecords.yaml
components:
  schemas:
    roles:
      type: object
      properties:
        roles:
          type: array
          items:
            type: object
            properties:
              value:
                $ref: ./components/schemas/TradePartyEnum.yaml
              display:
                type: string
                description: Friendly description of the trade party role
            required:
              - code
              - description
    contact:
      type: object
      properties:
        contactId:
          type: string
          example: UUID-123-234
        contactType:
          allOf:
            - description: Contact type.
            - $ref: ./components/schemas/ContactTypeEnum.yaml
        contactInfo:
          type: string
          example: 'https://foo.bar'
        nickname:
          type: string
          example: JohnDoe
        verified:
          type: boolean
          example: false
